---

- name: apt-get update
  apt: update_cache=yes

- name: apt-get upgrade
  apt: upgrade=full

- name: apt-get install build-essential
  apt: name=build-essential

# Utility

- name: Install system utility
  apt: pkg={{ item }}
  with_items:
    - htop
    - git-core
    - sysv-rc-conf


# Python

- name: Install Python packages
  apt: pkg={{ item }}
  with_items:
    - python-dev
    - python-pip

# Secure

- name: apt-get install sshguard
  apt: name=sshguard

- name: configure sshd_config
  lineinfile: dest=/etc/ssh/sshd_config
              owner=root group=root mode=0644
              backup=yes
              "regexp={{ item.regexp }}"
              "line={{ item.line }}"
              "insertafter={{ item.insertafter }}"
  with_items:
    - regexp: '^PasswordAuthentication'
      line: 'PasswordAuthentication no'
      insertafter: '#PasswordAuthentication'
    # - regexp: '^PermitRootLogin'
      # line: 'PermitRootLogin no'
      # insertafter: '#PermitRootLogin'
    - regexp: '^GSSAPIAuthentication'
      line: 'GSSAPIAuthentication no'
      insertafter: '#GSSAPIAuthentication'
  notify: restart sshd
